name: Pull Request Stats

on: issue_comment

jobs: 
  yuan:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: |
          echo "1"
          echo ${github.event}
          echo "2"
          echo ${github.event.requested.name}
          echo "3"
