name: Pull Request Stats

on: 
  pull_request:
    types: [review_requested]

jobs: 
  yuan:
    runs-on: ubuntu-latest
    steps:
      - name: log
        run: |
          echo "1"
          echo "${{ github.event }}"
          echo "2i"
          echo "${{ github.event.requested.name }}"
          echo "3"
