name: Pull Request Stats

on: 
  pull_request:
    types: [review_requested]

jobs: 
  yuan:
    runs-on: ubuntu-latest
    steps:
      - name: log
        run: |
          echo "1"
          echo "${{ github.ref_name }}"
          echo "2"
          echo "${{ github.ref }}"
          echo "3"
          echo "${{ env.BRANCH_NAME }}"
          echo "4"
          echo "${{ env.JOB_NAME }}"
          echo "5"
          echo "${{ github.event.pull_request.number }}"
          echo "6"
          echo "${{ toJson(github.event.pull_request) }}"
          echo "7"
          echo "${{ toJson(github.event) }}"
          echo "8"
          echo "${{ github.event.label.name }}"




