name: Pull Request Stats

on: issue_comment

jobs: 
  yuan:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: |
          echo "test"
          echo "${{github.event.pull_request.title}}"
