name: Pull Request Stats

on: 
  pull_request:
    types: [review_requested]

jobs: 
  yuan:
    runs-on: ubuntu-latest
    steps:
      - name: log
        run: |
          echo "1"
          echo "${{ github.event.pull_request.title }}"
          echo "1a"
          echo "${{ contains(github.event.pull_request.title, 'abc') }}"
          echo "2"
          echo "${{ toJson(github.event.pull_request.labels) }}"
          echo "3"
          echo "${{ env.BRANCH_NAME }}"
          echo "4"
          echo "${{ env.JOB_NAME }}"
          echo "5"
          echo "${{ github.event.pull_request.number }}"
          echo "6"
          echo "${{ toJson(github.event.pull_request) }}"
          echo "7"
          echo "${{ toJson(github.event) }}"
          echo "8"
          echo "${{ github.event.label.name }}"




