name: Pull Request Stats

on: 
  pull_request:
    types: [opened]

jobs:
  stats:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.title == '[DO NOT MERGE] pull-request-stats'}}
    steps:
      - name: Run pull request stats
        uses: flowwer-dev/pull-request-stats@master
        with:
          period: 7
          disable-links: true
          telemetry: false
