name: Pull Request Stats

on: 
  pull_request:
    types: [labeled]

jobs:
  run_if:
    if: contains(github.event.pull_request.labels.*.name, 'pull-request-stats')
    runs-on: ubuntu-latest
    steps:
      - name: Run pull request stats
        uses: flowwer-dev/pull-request-stats@master
        with:
          period: 7
          disable-links: true
          telemetry: false
