name: Pull Request Stats

on: 
  pull_request:
    types: [opened]

jobs:
  run_if:
    if: ${{ github.event.pull_request.title == '[DO NOT MERGE] pull-request-stats'}}
    runs-on: ubuntu-latest
    steps:
      - name: Run pull request stats
        uses: flowwer-dev/pull-request-stats@master
        with:
          period: 7
          disable-links: true
          telemetry: false
